//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalPocket.DataBaseFiles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DigitalPocketContext : DbContext
    {
        public DigitalPocketContext()
            : base("name=DigitalPocketContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PocketUser> PocketUser { get; set; }
        public DbSet<Transaction> Transaction { get; set; }
        public DbSet<UWallet> UWallet { get; set; }
    }
}
