//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalPocket.DataBaseFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string TransactionName { get; set; }
        public string Type { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> Ammount { get; set; }
        public string OriginAccount { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Note { get; set; }
    
        public virtual PocketUser PocketUser { get; set; }
    }
}
